from abc import ABC
from collections.abc import Mapping, MutableMapping
from typing import Any, Final, overload, Protocol, override


class MappingLike[K, V](Protocol):
    def __getitem__(self, item: K, /) -> V: ...
    @overload
    def get(self, key: K, default: None = None, /) -> V | None: ...
    @overload
    def get(self, key: K, default: V, /) -> V: ...
    @overload
    def get(self, key: K, default: V | None, /) -> V | None: ...
    @overload
    def get[U](self, key: K, default: V | U, /) -> V | U: ...
    @overload
    def get[U](self, key: K, default: V | U | None, /) -> V | U | None: ...

class MutableMappingLike[K, V](MappingLike[K, V], Protocol):
    def __setitem__(self, key: K, value: V | None, /): ...
    def __delitem__(self, key: K): ...

class _BaseAccessor[T](ABC):
    __field: Final[Mapping[str, T]]
    _children: Final[MutableMapping[str, _BaseAccessor[Any]]]

    @classmethod
    @overload
    def new[U](cls, obj: MutableMapping[str, U], /) -> MutableMappingAccessor[U]: ...
    @classmethod
    @overload
    def new[U](cls, obj: Mapping[str, U], /) -> MappingAccessor[U]: ...

    @property
    def _actual(self) -> Mapping[str, T]: ...

class MappingAccessor[T](_BaseAccessor[T], MappingLike[str, T]):
    def __init__(self, obj: Mapping[str, T], /): ...
    def __getattr__(self, key: str, /) -> T: ...

class MutableMappingAccessor[T](MappingAccessor[T], MutableMappingLike[str, T]):
    def __init__(self, obj: MutableMapping[str, T], /): ...
    def __setattr__(self, key: str, value: T, /): ...

    @override
    @property
    def _actual(self) -> MutableMapping[str, T]: ...

@overload
def accessor[T](obj: MutableMapping[str, T], /) -> MutableMappingAccessor[T]: ...
@overload
def accessor[T](obj: Mapping[str, T], /) -> MappingAccessor[T]: ...
